name       : easystroke
version    : 0.6.0
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/easystroke/easystroke/0.6.0/easystroke-0.6.0.tar.gz : f4c37adbc4dd405a24badb9e6be20d3223b4087ff9caed2c15ff71674051d0fd
license    : ISC
summary    : Easystroke is a gesture-recognition application for X11.
description: |
    Easystroke is a gesture-recognition application for X11. Gestures or strokes are movements that you make with you mouse (or your pen, finger etc.) while holding down a specific mouse button. Easystroke will execute certain actions if it recognizes the stroke; currently easystroke can emulate key presses, execute shell commands, hold down modifiers and emulate a scroll wheel. The program was designed with Tablet PCs in mind and can be used effectively even without access to a keyboard. Easystroke tries to provide an intuitive and efficient user interface, while at the same time being highly configurable and offering many advanced features.
builddeps  :
    - libboost-devel
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(xtst)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(xorg-server)
setup      : |
    %patch -p1 < $pkgfiles/replace-sigc-group-with-lambda.patch
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
