name       : easystroke
version    : 0.6.0
release    : 15
source     :
    - https://github.com/thjaeger/easystroke/archive/0.6.0.tar.gz : 425e4582ccf27f6bf77046b9fd2348325f9e3e105967bb475df201f11a18920d
license    : ISC
component  : desktop
summary    : Easystroke is a gesture-recognition application for X11.
description: |
    Easystroke is a gesture-recognition application for X11. Gestures or strokes are movements that you make with you mouse (or your pen, finger etc.) while holding down a specific mouse button. Easystroke will execute certain actions if it recognizes the stroke; currently easystroke can emulate key presses, execute shell commands, hold down modifiers and emulate a scroll wheel. The program was designed with Tablet PCs in mind and can be used effectively even without access to a keyboard. Easystroke tries to provide an intuitive and efficient user interface, while at the same time being highly configurable and offering many advanced features.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/replace-sigc-group-with-lambda.patch
    %patch -p1 < $pkgfiles/easystroke-0.6.0-abs.patch
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
