name       : easystroke
version    : 0.6.0
release    : 20
source     :
    - git|https://github.com/berkeleybross/easy-gesture.git : 0694a89eb5f7a4f1068d2e2b6960703923c0624e
license    : ISC
component  : desktop
summary    : Easystroke is a gesture-recognition application for X11.
description: |
    Easystroke is a gesture-recognition application for X11. Gestures or strokes are movements that you make with you mouse (or your pen, finger etc.) while holding down a specific mouse button. Easystroke will execute certain actions if it recognizes the stroke; currently easystroke can emulate key presses, execute shell commands, hold down modifiers and emulate a scroll wheel. The program was designed with Tablet PCs in mind and can be used effectively even without access to a keyboard. Easystroke tries to provide an intuitive and efficient user interface, while at the same time being highly configurable and offering many advanced features.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(xorg-server)
    - pkgconfig(xtst)
    - libboost-devel
setup      : |
    %cmake_ninja -S service
build      : |
    %ninja_build
install    : |
    install -Dm00755 $workdir/solusBuildDir/easygestured $installdir/usr/bin/easystroke
